name: build
run-name: page build

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  build-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Generate Page
        run: pnpm run generate

      - name: Push to release branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./.output/public
          branch: 'release'
